### ISSUE TITLE
2020.1_b19: Errors appearing in Homeassistant log

### ISSUE THREAD

**Issue by CaptInsano** [Pyhive/HA-Hive-Custom-Component#16]
This may just be a cosmetic issue but wanted to report it just incase

Hive integration is working correctly, there are no debug options enabled but Home Assistant Log showing following errors:

```
2020-11-09 21:05:28 ERROR (MainThread) [pyhiveapi.custom_logging] ERROR - No data found for device - Ground Floor
2020-11-09 21:05:30 ERROR (MainThread) [homeassistant.helpers.entity] Update for switch.boost_hot_water fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 278, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 474, in async_device_update
    raise exc
  File "/config/custom_components/hive/switch.py", line 99, in async_update
    if self.device["hive_type"] == "activeplug":
KeyError: 'hive_type'
2020-11-09 21:06:00 ERROR (MainThread) [homeassistant.helpers.entity] Update for switch.boost_hot_water fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 278, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 474, in async_device_update
    raise exc
  File "/config/custom_components/hive/switch.py", line 99, in async_update
    if self.device["hive_type"] == "activeplug":
KeyError: 'hive_type'
```

**Comment by CaptInsano** [comment]
Fixed in Beta 19

**Comment by CaptInsano** [comment]
Reopened.

Sorry, my mistake: still present in b19:

```
KeyError: 'hive_type'
2020-11-15 15:51:30 ERROR (MainThread) [homeassistant.helpers.entity] Update for switch.boost_hot_water fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 278, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 474, in async_device_update
    raise exc
  File "/config/custom_components/hive/switch.py", line 93, in async_update
    if self.device["hive_type"] == "activeplug":
KeyError: 'hive_type'
2020-11-15 15:51:58 ERROR (MainThread) [homeassistant.helpers.entity] Update for switch.boost_hot_water fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 278, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 474, in async_device_update
    raise exc
  File "/config/custom_components/hive/switch.py", line 93, in async_update
    if self.device["hive_type"] == "activeplug":
KeyError: 'hive_type'
2020-11-15 15:52:30 ERROR (MainThread) [homeassistant.helpers.entity] Update for switch.boost_hot_water fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 278, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 474, in async_device_update
    raise exc
  File "/config/custom_components/hive/switch.py", line 93, in async_update
    if self.device["hive_type"] == "activeplug":
KeyError: 'hive_type'
```

**Comment by holdestmade** [comment]
Getting same issue in B19, (1000 log entries in 2 hours)

**Comment by holdestmade** [comment]
b20 seems to have sorted this for me

**Comment by KJonline** [comment]
I haven’t done anything to fix the yet so that’s surprising?

**Comment by holdestmade** [comment]
Mmm, yes sure is, updated about 6 hours ago and nothing in logs

**Comment by CaptInsano** [comment]
Yeah looks fixed here too in beta 21 (may have been fixed in b20)

Issue closed
