### ISSUE TITLE
b19: Unable to call HotWater boost service: "Failed to call service hive/boost_hot_water. string indices must be integers"

### ISSUE THREAD

**Issue by CaptInsano** [Pyhive/HA-Hive-Custom-Component#17]
I am trying to set up a Boost Hot Water service as per: https://www.home-assistant.io/integrations/hive/

```
      - service: "hive.boost_hot_water"
        data:
          entity_id: "water_heater.hotwater"
          time_period: "01:00:00"
          on_off: "on"
```

![image](https://user-images.githubusercontent.com/332478/99101803-05c52500-25d5-11eb-8005-bed9d4be2947.png)

When I try to run the service I get the following pop-up error:

"Failed to call service hive/boost_hot_water. string indices must be integers"

The HomeAssistant log shows the following:

```
2020-11-13 17:23:14 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.140699679918400] string indices must be integers
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 135, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1448, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1483, in _execute_service
    await handler.job.target(service_call)
  File "/config/custom_components/hive/__init__.py", line 175, in hot_water_boost
    await hive.hotwater.turn_boost_on(node_id, minutes)
  File "/usr/local/lib/python3.8/site-packages/pyhiveapi/hotwater.py", line 185, in turn_boost_on
    await self.log.log(device["hive_id"], "Extra", "Turning on boost")
TypeError: string indices must be integers
```

**Comment by CaptInsano** [comment]
@KJonline I am really not trying to be a pain to you, just trying to provide best debug reports possible!!

Boost Service is working in b20 but Boost status ( sensor.ground_floor_boost_2) is no longer reporting boost being on. This error also appears in log:

```
2020-11-17 22:58:22 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.ground_floor_boost_2 fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 278, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 474, in async_device_update
    raise exc
  File "/config/custom_components/hive/sensor.py", line 139, in async_update
    endsin = await self.hive.hotwater.get_boost_time(self.device)
  File "/usr/local/lib/python3.8/site-packages/pyhiveapi/hotwater.py", line 101, in get_boost_time
    if await self.get_boost(device["hive_id"]) == "ON":
  File "/usr/local/lib/python3.8/site-packages/pyhiveapi/hotwater.py", line 82, in get_boost
    await self.log.log(device["hive_id"], "Extra", "Getting boost")
TypeError: string indices must be integers
2020-11-17 22:58:51 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.ground_floor_boost_2 fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 278, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 474, in async_device_update
    raise exc
  File "/config/custom_components/hive/sensor.py", line 139, in async_update
    endsin = await self.hive.hotwater.get_boost_time(self.device)
  File "/usr/local/lib/python3.8/site-packages/pyhiveapi/hotwater.py", line 101, in get_boost_time
    if await self.get_boost(device["hive_id"]) == "ON":
  File "/usr/local/lib/python3.8/site-packages/pyhiveapi/hotwater.py", line 82, in get_boost
    await self.log.log(device["hive_id"], "Extra", "Getting boost")
TypeError: string indices must be integers
```

**Comment by KJonline** [comment]
@CaptInsano dont worry about it hard working blind with the hotwater stuff so the process is taking a bit longer to get things correct. But I appreciate the bug reports, at least until the bugs have have gone.

**Comment by KJonline** [comment]
@CaptInsano please can you update to beta 21 and advise if you get any more issues with boosting?

**Comment by CaptInsano** [comment]
Fixed in b21!!

Boost reporting correctly and no more errors appearing logs!
