### ISSUE TITLE
2020.1_b19 Update for switch Errors in logs

### ISSUE THREAD

**Issue by holdestmade** [Pyhive/HA-Hive-Custom-Component#18]
This is appearing in my logs in the latest B19 (lots of times, nearly a thousand in 2 hours)

I have no active plugs

```
Logger: homeassistant.helpers.entity
Source: custom_components/hive/switch.py:93
First occurred: 14:13:46 (980 occurrences)
Last logged: 16:15:46

Update for switch.boost_heating fails
Update for switch.heating_off fails
Update for switch.boost_hot_water fails
Update for switch.hot_water_off fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 278, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 474, in async_device_update
    raise exc
  File "/config/custom_components/hive/switch.py", line 93, in async_update
    if self.device["hive_type"] == "activeplug":
KeyError: 'hive_type'
```

**Comment by holdestmade** [comment]
Sorry, noticed already an issue open
