### ISSUE TITLE
Invalid Config Error

### ISSUE THREAD

**Issue by rjenx** [Pyhive/HA-Hive-Custom-Component#2]
Hi, I had to rebuild my network due to an AP failure. While fixing the issues my hive integration suddenly stopped working. I tried re-installing the hive component but got the following error, I am not sure what to do as the only config I am aware of is the inclusion of the username and password in secrets and appropriate Hive: config in the config file. Can you suggest where I might start with this issue?  Thanks for your assistance. 

My HA is 0.113.3 running in a docker container on Synology NAS. 

Error during setup of component hive
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 193, in _async_setup_component
    result = await asyncio.wait_for(task, SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.8/asyncio/tasks.py", line 483, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/hive/__init__.py", line 125, in setup
    devices = session.core.initialise_api(username, password, update_interval)
  File "/usr/local/lib/python3.8/site-packages/pyhiveapi/pyhiveapi.py", line 767, in initialise_api
    if product["parent"] == device["props"]["zone"]:
KeyError: 'zone'

**Comment by rjenx** [comment]
Sorry, a switch misconfiguration caused the problem. Now resolved.
