### ISSUE TITLE
2020.1_b2: Error: Attempt to decode JSON with unexpected mimetype

### ISSUE THREAD

**Issue by CaptInsano** [Pyhive/HA-Hive-Custom-Component#3]
I just installed a hive multizone heating system and installed this custom component via HACs to homeassistant latest (114.2) on a hassio install but it is not finding my devices:

![image](https://user-images.githubusercontent.com/332478/90563489-d3558880-e19b-11ea-8ec7-d57a20eba57b.png)

My configuration.yaml contains:

```
hive:
  username: myemail@address.com
  password: mypassword
```

HomeAssistant log on start:

`2020-08-18 21:11:23 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for hive which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.`

No other mention of hive in the log after this, no hive entities or states in developer options.

I have confirmed the username and password are correct many times via logging in to https://my.hivehome.com/

The result is the same if I use this custom integration or if I use the native hive integration in homeassistant (minus the custom integration warning in log).

I am based in Ireland, I am unsure if that affects anything?

Any advice? I am willing to provide any debugging support I can.

**Comment by CaptInsano** [comment]
I installed the most recent beta of this integration and this time got some errors in the log when trying to setup the integration in the UI:

```
2020-08-19 21:04:00 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/real_ip.py", line 39, in real_ip_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 73, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 127, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 129, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 145, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 60, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 106, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 153, in async_configure
    result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 201, in _async_handle_step
    result: Dict = await getattr(flow, method)(user_input)
  File "/config/custom_components/hive/config_flow.py", line 68, in async_step_user
    token_request = await self.hive.create_token(login_token)
  File "/usr/local/lib/python3.8/site-packages/pyhiveapi/hive_async_api.py", line 85, in create_token
    await self.request('post', url,  data=j)
  File "/usr/local/lib/python3.8/site-packages/pyhiveapi/hive_async_api.py", line 44, in request
    await resp.json()
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1026, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: application/*+json;charset=utf-8', url=URL('https://api.prod.bgchprod.info/omnia/accessTokens')
```

Any advice would be greatly appreciated

**Comment by cwelsh1812** [comment]
I'd like to add that I am having the same issue although I am using the UK version of Hive.

**Comment by KJonline** [comment]
Hi @CaptInsano 

Thank you for reporting this issue in the beta. The beta version is a complete re design of the hive backend package. This error you are seeing is part of the upgrade to use long lived tokens instead of logging in with your username and password every 15 mins.  My guess is even you got past this issue you would still have the same problem where it wasn’t recognising your  devices.

I’ll reach out to you in the HA community in a private message to advise how you can extract your hive data for us to review. I need to warn you though that extracting data from hives website will include personal data and unique device data. Please review the data and anonymise it before publishing it.

**Comment by cwelsh1812** [comment]
> I'd like to add that I am having the same issue although I am using the UK version of Hive.

The latest version 2020.0 has fixed my issue and my Hive entities are now all showing again.
