### ISSUE TITLE
Water Heater Component Issue

### ISSUE THREAD

**Issue by nil-ghosh** [Pyhive/HA-Hive-Custom-Component#30]
Version: Beta 21 - Configured through UI.

Issue 1: Following sensors are not showing up in entities list: hotwater state and hotwater mode)

Issue 2: Turning off hot water boost gives the following error: (No issues while turning on)

Logger: homeassistant.helpers.script.hotwater_boost
Source: custom_components/hive/__init__.py:177
First occurred: December 4, 2020, 11:36:21 AM (3 occurrences)
Last logged: December 4, 2020, 11:40:06 AM

hotwater_boost: Error executing script. Unexpected error for call_service at pos 2: string indices must be integers
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/script.py", line 247, in _async_step
    await getattr(
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/script.py", line 454, in _async_call_service_step
    await service_task
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/core.py", line 1335, in async_call
    task.result()
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/core.py", line 1370, in _execute_service
    await handler.func(service_call)
  File "/home/homeassistant/.homeassistant/custom_components/hive/__init__.py", line 177, in hot_water_boost
    await hive.hotwater.turn_boost_off(device)
  File "/srv/homeassistant/lib/python3.9/site-packages/pyhiveapi/hotwater.py", line 209, in turn_boost_off
    if device["hive_id"] in Data.products and await self.get_boost(device["hive_id"]) == "ON":
  File "/srv/homeassistant/lib/python3.9/site-packages/pyhiveapi/hotwater.py", line 82, in get_boost
    await self.log.log(device["hive_id"], "Extra", "Getting boost")
TypeError: string indices must be integers

**Comment by KJonline** [comment]
Fix released in Beta 23
