### ISSUE TITLE
[BUG] b25_ Unable to start HotWater from script [async error]

### ISSUE THREAD

**Issue by CaptInsano** [Pyhive/HA-Hive-Custom-Component#47]
**Describe the bug**

When trying to call Hot Water from Script I get the following error:

`'HiveWaterHeater' object has no attribute 'async_turn_on'`

**To Reproduce**
![image](https://user-images.githubusercontent.com/332478/102016045-c36b4100-3d56-11eb-8f24-ec81f293f3e2.png)

**Expected behaviour**
Hot Water should turn on or off depending on settings choosen in script setup.

**Screenshots**
See above.

**HomeAssistant Log**
```
2020-12-13 15:17:32 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [139971280569008] 'HiveWaterHeater' object has no attribute 'async_turn_on'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 135, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1451, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1486, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/components/script/__init__.py", line 215, in service_handler
    await script_entity.async_turn_on(
  File "/usr/src/homeassistant/homeassistant/components/script/__init__.py", line 320, in async_turn_on
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1010, in async_run
    await asyncio.shield(run.async_run())
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 245, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 253, in _async_step
    await getattr(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 472, in _async_device_step
    await platform.async_call_action_from_config(
  File "/usr/src/homeassistant/homeassistant/components/water_heater/device_action.py", line 73, in async_call_action_from_config
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1451, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1486, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 499, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 664, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 530, in _handle_entity_call
    result = hass.async_add_job(partial(getattr(entity, func), **data))  # type: ignore
AttributeError: 'HiveWaterHeater' object has no attribute 'async_turn_on'
```

**Comment by KJonline** [comment]
Hi @CaptInsano i don’t think there is an off/on option in the hive app for hotwater like there is for heating it’s just modes??

I believe the hotwater function in the hive app just changes the mode?

**Comment by CaptInsano** [comment]
There is an on / off option in the app:

![image](https://user-images.githubusercontent.com/332478/102017412-c10ce500-3d5e-11eb-814e-d3028ccd4c82.png)

**Comment by CaptInsano** [comment]
@KJonline Anything I can do to help debug this Dev?

I want to use the Scheduler component from HACS but I need to create a script inorder to trigger hotwater state.
(Scheduler component works for climate entities but hotwater is not listed as a climate entity.)

As always, thanks so much for all your work on this.

**Comment by KJonline** [comment]
Fixed with latest release please reopen if still an issue
