### ISSUE TITLE
[BUG] - Calling light.turn_off when light is offline throws an error

### ISSUE THREAD

**Issue by perjury** [Pyhive/HA-Hive-Custom-Component#49]
**Describe the bug**
Calling light.turn_off when light is offline throws a 'bad request' error

**To Reproduce**
Steps to reproduce the behaviour:
1. Switch lamp fixture off at the mains so that Hive bulb is offline
2. Execute service light.turn_off for that bulb 
3. Error shows in log

**Expected behaviour**
Service call should not throw an error

**Screenshots**
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/hive/light.py:133
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 11:26:30 (2 occurrences)
Last logged: 11:29:34

[1714693024] Bad Request
[1726690064] Bad Request
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 135, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1445, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1480, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 593, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 664, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 630, in _handle_entity_call
    await result
  File "/config/custom_components/hive/__init__.py", line 229, in wrapper
    await func(self, *args, **kwargs)
  File "/config/custom_components/hive/light.py", line 133, in async_turn_off
    await self.hive.light.turn_off(self.device)
  File "/usr/local/lib/python3.8/site-packages/pyhiveapi/light.py", line 178, in turn_off
    resp = await self.hive.set_state(data["type"],
  File "/usr/local/lib/python3.8/site-packages/pyhiveapi/hive_async_api.py", line 196, in set_state
    await self.request('post', url,  data=jsc)
  File "/usr/local/lib/python3.8/site-packages/pyhiveapi/hive_async_api.py", line 73, in request
    raise HTTPBadRequest
aiohttp.web_exceptions.HTTPBadRequest: Bad Request

**Additional context**
I have a script which turns off a group containing Hive bulbs which may or may not be offline. This causes script to terminate before it completes. This did not used to be the case.

Currently using version 2020.12.0
Component b25

**Comment by perjury** [comment]
Workaround - remove any light groups used in the Hive App

**Comment by perjury** [comment]
I spoke too soon.
Some of my offline -off at the switch - lights are now reporting as 'on' when they should be reporting as 'unavailable' and I now get the bad request error message again

**Comment by KJonline** [comment]
Fixed with latest release please reopen if still an issue
