### ISSUE TITLE
2020.1_b3 Error: No module named 'curlify'

### ISSUE THREAD

**Issue by CaptInsano** [Pyhive/HA-Hive-Custom-Component#5]
Updated to 2020.1_b3 when I got the alert from HACS

After updating HomeAssistant would not complete its startup process, it gets stuck on 
"Home Assistant is starting, not everything will be available until it is finished."

The logs show the following:

```
[services.d] starting services
[services.d] done.
2020-10-03 20:41:39 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for hive which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-10-03 20:41:39 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for blueiris which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-10-03 20:41:39 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for garbage_collection which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-10-03 20:41:39 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-10-03 20:41:50 WARNING (MainThread) [homeassistant.setup] Setup of recorder is taking over 10 seconds.
2020-10-03 20:42:02 WARNING (Recorder) [homeassistant.components.recorder] Ended unfinished session (id=29 from 2020-10-03 19:31:06.887179)
2020-10-03 20:42:04 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading configuration flow for integration hive: No module named 'curlify'
2020-10-03 20:42:06 ERROR (MainThread) [homeassistant.components.brother] Error fetching brother data: Bad IPv4/UDP transport address BrotherPrinter5.local@161: [Errno -2] Name does not resolvecaused by <class 'socket.gaierror'>: [Errno -2] Name does not resolve
2020-10-03 20:42:06 WARNING (MainThread) [homeassistant.config_entries] Config entry for brother not ready yet. Retrying in 5 seconds
2020-10-03 20:42:11 ERROR (MainThread) [homeassistant.components.brother] Error fetching brother data: Bad IPv4/UDP transport address BrotherPrinter5.local@161: [Errno -2] Name does not resolvecaused by <class 'socket.gaierror'>: [Errno -2] Name does not resolve
2020-10-03 20:42:11 WARNING (MainThread) [homeassistant.config_entries] Config entry for brother not ready yet. Retrying in 10 seconds
2020-10-03 20:42:21 ERROR (MainThread) [homeassistant.components.brother] Error fetching brother data: Bad IPv4/UDP transport address BrotherPrinter5.local@161: [Errno -2] Name does not resolvecaused by <class 'socket.gaierror'>: [Errno -2] Name does not resolve
2020-10-03 20:42:21 WARNING (MainThread) [homeassistant.config_entries] Config entry for brother not ready yet. Retrying in 20 seconds
2020-10-03 20:42:42 ERROR (MainThread) [homeassistant.components.brother] Error fetching brother data: Bad IPv4/UDP transport address BrotherPrinter5.local@161: [Errno -2] Name does not resolvecaused by <class 'socket.gaierror'>: [Errno -2] Name does not resolve
2020-10-03 20:42:42 WARNING (MainThread) [homeassistant.config_entries] Config entry for brother not ready yet. Retrying in 40 seconds
2020-10-03 20:43:04 WARNING (MainThread) [homeassistant.bootstrap] Waiting on integrations to complete setup: hive
2020-10-03 20:43:22 ERROR (MainThread) [homeassistant.components.brother] Error fetching brother data: Bad IPv4/UDP transport address BrotherPrinter5.local@161: [Errno -2] Name does not resolvecaused by <class 'socket.gaierror'>: [Errno -2] Name does not resolve
2020-10-03 20:43:22 WARNING (MainThread) [homeassistant.config_entries] Config entry for brother not ready yet. Retrying in 80 seconds
2020-10-03 20:44:04 WARNING (MainThread) [homeassistant.bootstrap] Waiting on integrations to complete setup: hive
2020-10-03 20:45:04 WARNING (MainThread) [homeassistant.bootstrap] Waiting on integrations to complete setup: hive
2020-10-03 20:46:04 WARNING (MainThread) [homeassistant.bootstrap] Waiting on integrations to complete setup: hive
2020-10-03 20:47:04 WARNING (MainThread) [homeassistant.bootstrap] Setup timed out for stage 2 - moving forward
2020-10-03 20:47:04 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 527, in async_create_flow
    integration.get_platform("config_flow")
  File "/usr/src/homeassistant/homeassistant/loader.py", line 401, in get_platform
    cache[full_name] = importlib.import_module(
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/custom_components/hive/config_flow.py", line 12, in <module>
    from pyhiveapi import Hive_Async, Session
  File "/usr/local/lib/python3.8/site-packages/pyhiveapi/__init__.py", line 2, in <module>
    from .hive_session import Session
  File "/usr/local/lib/python3.8/site-packages/pyhiveapi/hive_session.py", line 16, in <module>
    from .hive_async_api import Hive_Async
  File "/usr/local/lib/python3.8/site-packages/pyhiveapi/hive_async_api.py", line 3, in <module>
    import curlify
ModuleNotFoundError: No module named 'curlify'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 120, in async_init
    flow = await self.async_create_flow(handler, context=context, data=data)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 534, in async_create_flow
    raise data_entry_flow.UnknownHandler
homeassistant.data_entry_flow.UnknownHandler
2020-10-03 20:47:04 WARNING (MainThread) [homeassistant.bootstrap] Waiting on integrations to complete setup: hive
```

Hope this helps

**Comment by KJonline** [comment]
@CaptInsano Yes I picked up on this issue and have created 2 new betas testing this. Beta 5 should fix the issues.
