### ISSUE TITLE
Issue adding entities after removing and re-adding the component

### ISSUE THREAD

**Issue by tristophe** [Pyhive/HA-Hive-Custom-Component#58]
This is a really great component but recently I have been getting an error with colour devices.

Previously the colour lights were added successfully but recently they have appeared disabled so I removed and re-added the component. The other sensors related to the bulbs (availability and mode) but the actual bulb entity doesn't show up.

Log is below, any help or advice really appreciated!

Traceback (most recent call last):,
2021-01-27 18:27:40 ERROR (MainThread) [homeassistant.components.light] hive: Error on device update!,
TypeError: unsupported operand type(s) for /: 'NoneType' and 'int',
    (data["state"]["hue"]) / 360,,
  File "/usr/local/lib/python3.8/site-packages/pyhiveapi/light.py", line 157, in get_color,
    dev_data["status"].update({"hs_color": await self.get_color(device)}),
  File "/usr/local/lib/python3.8/site-packages/pyhiveapi/light.py", line 56, in get_light,
    self.device = await self.hive.light.get_light(self.device),
    await task,
  File "/config/custom_components/hive/light.py", line 151, in async_update,
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 466, in async_device_update,
    await entity.async_device_update(warning=False),
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 359, in _async_add_entity

**Comment by KJonline** [comment]
Fixed with latest release please reopen if still an issue
