### ISSUE TITLE
2020.1_b15: Able to see a water_heater entity but unable to control it or see updates

### ISSUE THREAD

**Issue by CaptInsano** [Pyhive/HA-Hive-Custom-Component#6]
With the current latest version of this custom component (b5) I can see the water heater controls attached to my Ground Floor thermostat "water_heater.ground_floor", but when I try to control it (eg. turn it from "off" to "on") I get a brief popup saying:

"Failed to call service water_heater/set_operation_mode. 'coroutine' object is not subscriptable" 

and the following error in log and nothing happens to the state of the water heater..

```
2020-10-04 13:24:22 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.139623738001536] 'coroutine' object is not subscriptable
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 137, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1315, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1350, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 459, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 655, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 490, in _handle_entity_call
    await result
  File "/config/custom_components/hive/__init__.py", line 203, in wrapper
    await func(self, *args, **kwargs)
  File "/config/custom_components/hive/water_heater.py", line 108, in async_set_operation_mode
    await self.hive.hotwater.set_mode(self.device, new_mode)
  File "/usr/local/lib/python3.8/site-packages/pyhiveapi/hotwater.py", line 186, in set_mode
    if resp["original"] == 200:
TypeError: 'coroutine' object is not subscriptable
```

Hope this helps in debugging.

As always thanks for all your work.

**Comment by KJonline** [comment]
@CaptInsano Please can you give this a try now. I have updated the code but struggle to test I don't have hotwater in my setup.

**Comment by CaptInsano** [comment]
Updated to b6:
No errors reported in log (or popups) but the water heater is not turning on when I try to turn it on:

![image](https://user-images.githubusercontent.com/332478/95024885-c0304680-067d-11eb-8145-f1bdb5ecd5e6.png)


I am willing to try and help debug wherever possible.

**Comment by CaptInsano** [comment]
It also does not update it's state when I turn on the water heating from the Hive app

**Comment by KJonline** [comment]
@CaptInsano 

Sorry so do the functions work when you action them? I’ll look into the state not updating.

**Comment by CaptInsano** [comment]
Neither the function control work from HomeAssistant nor does the state update in HomeAssistant when the water is turned on in the Hive App

**Comment by CaptInsano** [comment]
Just added a lovelace button for water_heater.ground_floor, when I toggle the switch the following error pops up:

`Failed to call service water_heater/turn_on. 'HiveWaterHeater' object has no attribute 'async_turn_on'`

log shows:

```
2020-10-04 21:57:36 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.140670564743344] 'HiveWaterHeater' object has no attribute 'async_turn_on'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 137, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1315, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1350, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 459, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 655, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 484, in _handle_entity_call
    result = hass.async_add_job(partial(getattr(entity, func), **data))
AttributeError: 'HiveWaterHeater' object has no attribute 'async_turn_on'
```

**Comment by CaptInsano** [comment]
Just an update (hoping to aid development, not torment developer!)

In beta 10 I can still see hot-water entity (controlled via "Ground Floor" thermostat) but it is not correctly updated:

![image](https://user-images.githubusercontent.com/332478/98295406-75ba2680-1fa9-11eb-8024-4dc60cf66bdc.png)


![image](https://user-images.githubusercontent.com/332478/98295471-88346000-1fa9-11eb-8e58-9f8f79e6eb86.png)

**Comment by CaptInsano** [comment]
Also noticed that the homeassistant log is now filling up with:

```
2020-11-05 21:18:02 ERROR (MainThread) [pyhiveapi.custom_logging] ERROR - No data found for device.
2020-11-05 21:18:02 ERROR (MainThread) [pyhiveapi.custom_logging] ERROR - No data found for device.
2020-11-05 21:18:02 ERROR (MainThread) [pyhiveapi.custom_logging] ERROR - No data found for device.
2020-11-05 21:18:02 ERROR (MainThread) [pyhiveapi.custom_logging] ERROR - No data found for device.
2020-11-05 21:18:02 ERROR (MainThread) [pyhiveapi.custom_logging] ERROR - No data found for device.
2020-11-05 21:18:02 ERROR (MainThread) [pyhiveapi.custom_logging] ERROR - No data found for device.
2020-11-05 21:18:02 ERROR (MainThread) [pyhiveapi.custom_logging] ERROR - No data found for device.
2020-11-05 21:18:02 ERROR (MainThread) [pyhiveapi.custom_logging] ERROR - No data found for device.
2020-11-05 21:18:02 ERROR (MainThread) [pyhiveapi.custom_logging] ERROR - No data found for device.
2020-11-05 21:18:02 ERROR (MainThread) [pyhiveapi.custom_logging] ERROR - No data found for device.
2020-11-05 21:18:03 ERROR (MainThread) [pyhiveapi.custom_logging] ERROR - No data found for device.
2020-11-05 21:18:03 ERROR (MainThread) [pyhiveapi.custom_logging] ERROR - No data found for device.
2020-11-05 21:18:03 ERROR (MainThread) [pyhiveapi.custom_logging] ERROR - No data found for device.
2020-11-05 21:18:03 ERROR (MainThread) [pyhiveapi.custom_logging] ERROR - No data found for device.
2020-11-05 21:18:03 ERROR (MainThread) [pyhiveapi.custom_logging] ERROR - No data found for device.
2020-11-05 21:18:03 ERROR (MainThread) [pyhiveapi.custom_logging] ERROR - No data found for device.
2020-11-05 21:18:03 ERROR (MainThread) [pyhiveapi.custom_logging] ERROR - No data found for device.
2020-11-05 21:18:03 ERROR (MainThread) [pyhiveapi.custom_logging] ERROR - No data found for device.
2020-11-05 21:18:03 ERROR (MainThread) [pyhiveapi.custom_logging] ERROR - No data found for device.
2020-11-05 21:18:03 ERROR (MainThread) [pyhiveapi.custom_logging] ERROR - No data found for device.
2020-11-05 21:18:03 ERROR (MainThread) [pyhiveapi.custom_logging] ERROR - No data found for device.
2020-11-05 21:18:03 ERROR (MainThread) [pyhiveapi.custom_logging] ERROR - No data found for device.
2020-11-05 21:18:03 ERROR (MainThread) [pyhiveapi.custom_logging] ERROR - No data found for device.
2020-11-05 21:18:03 ERROR (MainThread) [pyhiveapi.custom_logging] ERROR - No data found for device.
2020-11-05 21:18:30 ERROR (MainThread) [pyhiveapi.custom_logging] ERROR - No data found for device.
2020-11-05 21:18:30 ERROR (MainThread) [pyhiveapi.custom_logging] ERROR - No data found for device.
2020-11-05 21:18:30 ERROR (MainThread) [pyhiveapi.custom_logging] ERROR - No data found for device.
2020-11-05 21:18:30 ERROR (MainThread) [pyhiveapi.custom_logging] ERROR - No data found for device.
2020-11-05 21:18:30 ERROR (MainThread) [pyhiveapi.custom_logging] ERROR - No data found for device.
2020-11-05 21:18:30 ERROR (MainThread) [pyhiveapi.custom_logging] ERROR - No data found for device.
2020-11-05 21:18:30 ERROR (MainThread) [pyhiveapi.custom_logging] ERROR - No data found for device.
2020-11-05 21:18:30 ERROR (MainThread) [pyhiveapi.custom_logging] ERROR - No data found for device.
2020-11-05 21:18:30 ERROR (MainThread) [pyhiveapi.custom_logging] ERROR - No data found for device.
2020-11-05 21:18:30 ERROR (MainThread) [pyhiveapi.custom_logging] ERROR - No data found for device.
2020-11-05 21:18:30 ERROR (MainThread) [pyhiveapi.custom_logging] ERROR - No data found for device.
2020-11-05 21:18:30 ERROR (MainThread) [pyhiveapi.custom_logging] ERROR - No data found for device.
2020-11-05 21:18:30 ERROR (MainThread) [pyhiveapi.custom_logging] ERROR - No data found for device.
2020-11-05 21:18:30 ERROR (MainThread) [pyhiveapi.custom_logging] ERROR - No data found for device.
2020-11-05 21:18:30 ERROR (MainThread) [pyhiveapi.custom_logging] ERROR - No data found for device.
2020-11-05 21:18:30 ERROR (MainThread) [pyhiveapi.custom_logging] ERROR - No data found for device.
2020-11-05 21:18:30 ERROR (MainThread) [pyhiveapi.custom_logging] ERROR - No data found for device.
2020-11-05 21:18:30 ERROR (MainThread) [pyhiveapi.custom_logging] ERROR - No data found for device.
2020-11-05 21:18:30 ERROR (MainThread) [pyhiveapi.custom_logging] ERROR - No data found for device.
2020-11-05 21:18:30 ERROR (MainThread) [pyhiveapi.custom_logging] ERROR - No data found for device.
2020-11-05 21:18:30 ERROR (MainThread) [pyhiveapi.custom_logging] ERROR - No data found for device.
```

Is that to do with the water heater entity?

**Comment by CaptInsano** [comment]
@KJonline 

Is there anything I can provide to help debug this issue?

Loads of progress made by you up to and including b15, would love to help fix this issue of Hot Water control if I can in any way

**Comment by KJonline** [comment]
@CaptInsano yes there is for debugging to work you need to add pyhiveapi into your logger component in your configuration.yaml.

![1506E4AE-5166-4852-89B6-5E7B4EE0A75C](https://user-images.githubusercontent.com/29937485/98402765-c55b2980-205f-11eb-9002-f40dbc147f02.jpeg)


Once you have put this into your configuration file and restarted  home assistant you can use the debug options via the UI to enable the relevant category. Please be aware there is a lot of logging so please switch on config like All at your own will but it will swamp your logs if you do. It may be worth switching them on one at a time. For this issue I would focus on hotwater, api and the session categories.

**Comment by CaptInsano** [comment]
Enabled those 3 debugging options (hot water, api and session) and the following is from my log (I removed some unique IDS)

```
[services.d] starting services
[services.d] done.
2020-11-06 19:16:43 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for hive which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-11-06 19:16:43 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-11-06 19:16:43 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for scheduler which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-11-06 19:16:43 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for garbage_collection which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-11-06 19:16:46 DEBUG (MainThread) [pyhiveapi.custom_logging] Initialising Hive Component.
2020-11-06 19:16:46 DEBUG (MainThread) [pyhiveapi.custom_logging] Scan interval updated to 0:00:30
2020-11-06 19:16:46 DEBUG (MainThread) [pyhiveapi.custom_logging] Logging into Hive.
2020-11-06 19:16:49 DEBUG (MainThread) [pyhiveapi.custom_logging] Getting hive device info
2020-11-06 19:16:49 DEBUG (MainThread) [pyhiveapi.custom_logging] Checking if new tokens are required
2020-11-06 19:16:49 DEBUG (MainThread) [pyhiveapi.custom_logging] Attempting to refresh tokens.
2020-11-06 19:16:49 DEBUG (MainThread) [pyhiveapi.custom_logging] Request is - post:https://beekeeper.hivehome.com/1.0/cognito/refresh-token
2020-11-06 19:16:51 DEBUG (MainThread) [pyhiveapi.custom_logging] Response is - 200
2020-11-06 19:16:51 DEBUG (MainThread) [pyhiveapi.custom_logging] Request is - get:https://beekeeper-uk.hivehome.com/1.0/nodes/all?products=true&devices=true&actions=true
2020-11-06 19:16:53 DEBUG (MainThread) [pyhiveapi.custom_logging] Response is - 200
2020-11-06 19:16:53 DEBUG (MainThread) [pyhiveapi.custom_logging] Getting Hive weather info.
2020-11-06 19:16:53 DEBUG (MainThread) [pyhiveapi.custom_logging] Checking if new tokens are required
2020-11-06 19:16:53 DEBUG (MainThread) [pyhiveapi.custom_logging] Request is - get:https://weather.prod.bgchprod.info/weather?postcode=&country=IE
2020-11-06 19:16:53 DEBUG (MainThread) [pyhiveapi.custom_logging] Response is - 400
2020-11-06 19:16:53 DEBUG (MainThread) [pyhiveapi.custom_logging] Creating list of devices
2020-11-06 19:16:53 DEBUG (MainThread) [pyhiveapi.custom_logging] Hive component has initialised
2020-11-06 19:16:55 DEBUG (MainThread) [pyhiveapi.custom_logging] Getting hot water data.
2020-11-06 19:16:55 DEBUG (MainThread) [pyhiveapi.custom_logging] Device update {'hive_id': '84dfaef3-93c5-4aab-9530-XXXXXXXXXX', 'hive_name': 'Ground Floor', 'hive_type': 'hotwater', 'ha_name': 'Ground Floor', 'ha_type': 'water_heater', 'device_id': 'c155cc26-4ce0-42ef-8a57-XXXXXXXXXX', 'device_name': 'Ground Floor', 'current_operation': 'OFF', 'device_data': {'online': True, 'presenceLastChanged': 1603418475672, 'model': 'SLT3', 'version': '05060212', 'manufacturer': 'Computime', 'upgrade': {'available': False, 'version': '05060212', 'progress': 100, 'upgrading': False, 'status': 'COMPLETE'}, 'power': 'battery', 'signal': 100, 'battery': 100, 'capabilities': ['INFORMATION', 'RENAME', 'HEATING_ALERTS', 'GEOLOCATION', 'HOLIDAY_MODE', 'OPTIMUM_START'], 'modelVariant': 'SLT3b', 'zone': 'f9efdf45-46a2-4157-8e6c-XXXXXXXXXX'}, 'parent_device': '0edeaee5-8436-4b91-b6b5-XXXXXXXXXX', 'custom': None, 'attributes': {'available': None}}
2020-11-06 19:16:56 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for blueiris which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-11-06 19:17:26 DEBUG (MainThread) [pyhiveapi.custom_logging] Getting hive device info
2020-11-06 19:17:26 DEBUG (MainThread) [pyhiveapi.custom_logging] Checking if new tokens are required
2020-11-06 19:17:26 DEBUG (MainThread) [pyhiveapi.custom_logging] Request is - get:https://beekeeper-uk.hivehome.com/1.0/nodes/all?products=true&devices=true&actions=true
2020-11-06 19:17:27 DEBUG (MainThread) [pyhiveapi.custom_logging] Response is - 200
2020-11-06 19:17:47 ERROR (MainThread) [homeassistant.components.google_assistant.http] Request for https://homegraph.googleapis.com/v1/devices:reportStateAndNotification failed: 404
2020-11-06 19:17:56 DEBUG (MainThread) [pyhiveapi.custom_logging] Getting hot water data.
2020-11-06 19:17:56 DEBUG (MainThread) [pyhiveapi.custom_logging] Device update {'hive_id': '84dfaef3-93c5-4aab-9530-XXXXXXXXXX', 'hive_name': 'Ground Floor', 'hive_type': 'hotwater', 'ha_name': 'Ground Floor', 'ha_type': 'water_heater', 'device_id': 'c155cc26-4ce0-42ef-8a57-XXXXXXXXXX', 'device_name': 'Ground Floor', 'current_operation': 'OFF', 'device_data': {'online': True, 'presenceLastChanged': 1603418475672, 'model': 'SLT3', 'version': '05060212', 'manufacturer': 'Computime', 'upgrade': {'available': False, 'version': '05060212', 'progress': 100, 'upgrading': False, 'status': 'COMPLETE'}, 'power': 'battery', 'signal': 100, 'battery': 100, 'capabilities': ['INFORMATION', 'RENAME', 'HEATING_ALERTS', 'GEOLOCATION', 'HOLIDAY_MODE', 'OPTIMUM_START'], 'modelVariant': 'SLT3b', 'zone': 'f9efdf45-46a2-4157-8e6c-XXXXXXXXXX'}, 'parent_device': '0edeaee5-8436-4b91-b6b5-XXXXXXXXXX', 'custom': None, 'attributes': {'available': None}}
2020-11-06 19:18:26 DEBUG (MainThread) [pyhiveapi.custom_logging] Getting hive device info
2020-11-06 19:18:26 DEBUG (MainThread) [pyhiveapi.custom_logging] Checking if new tokens are required
2020-11-06 19:18:26 DEBUG (MainThread) [pyhiveapi.custom_logging] Request is - get:https://beekeeper-uk.hivehome.com/1.0/nodes/all?products=true&devices=true&actions=true
2020-11-06 19:18:27 DEBUG (MainThread) [pyhiveapi.custom_logging] Response is - 200
2020-11-06 19:18:56 DEBUG (MainThread) [pyhiveapi.custom_logging] Getting hot water data.
2020-11-06 19:18:56 DEBUG (MainThread) [pyhiveapi.custom_logging] Device update {'hive_id': '84dfaef3-93c5-4aab-9530-XXXXXXXXXX', 'hive_name': 'Ground Floor', 'hive_type': 'hotwater', 'ha_name': 'Ground Floor', 'ha_type': 'water_heater', 'device_id': 'c155cc26-4ce0-42ef-8a57-XXXXXXXXXX', 'device_name': 'Ground Floor', 'current_operation': 'OFF', 'device_data': {'online': True, 'presenceLastChanged': 1603418475672, 'model': 'SLT3', 'version': '05060212', 'manufacturer': 'Computime', 'upgrade': {'available': False, 'version': '05060212', 'progress': 100, 'upgrading': False, 'status': 'COMPLETE'}, 'power': 'battery', 'signal': 100, 'battery': 100, 'capabilities': ['INFORMATION', 'RENAME', 'HEATING_ALERTS', 'GEOLOCATION', 'HOLIDAY_MODE', 'OPTIMUM_START'], 'modelVariant': 'SLT3b', 'zone': 'f9efdf45-46a2-4157-8e6c-XXXXXXXXXX'}, 'parent_device': '0edeaee5-8436-4b91-b6b5-XXXXXXXXXX', 'custom': None, 'attributes': {'available': None}}
2020-11-06 19:19:26 DEBUG (MainThread) [pyhiveapi.custom_logging] Getting hive device info
2020-11-06 19:19:26 DEBUG (MainThread) [pyhiveapi.custom_logging] Checking if new tokens are required
2020-11-06 19:19:26 DEBUG (MainThread) [pyhiveapi.custom_logging] Request is - get:https://beekeeper-uk.hivehome.com/1.0/nodes/all?products=true&devices=true&actions=true
2020-11-06 19:19:27 DEBUG (MainThread) [pyhiveapi.custom_logging] Response is - 200
2020-11-06 19:19:56 DEBUG (MainThread) [pyhiveapi.custom_logging] Getting hot water data.
2020-11-06 19:19:56 DEBUG (MainThread) [pyhiveapi.custom_logging] Device update {'hive_id': '84dfaef3-93c5-4aab-9530-XXXXXXXXXX', 'hive_name': 'Ground Floor', 'hive_type': 'hotwater', 'ha_name': 'Ground Floor', 'ha_type': 'water_heater', 'device_id': 'c155cc26-4ce0-42ef-8a57-XXXXXXXXXX', 'device_name': 'Ground Floor', 'current_operation': 'OFF', 'device_data': {'online': True, 'presenceLastChanged': 1603418475672, 'model': 'SLT3', 'version': '05060212', 'manufacturer': 'Computime', 'upgrade': {'available': False, 'version': '05060212', 'progress': 100, 'upgrading': False, 'status': 'COMPLETE'}, 'power': 'battery', 'signal': 100, 'battery': 100, 'capabilities': ['INFORMATION', 'RENAME', 'HEATING_ALERTS', 'GEOLOCATION', 'HOLIDAY_MODE', 'OPTIMUM_START'], 'modelVariant': 'SLT3b', 'zone': 'f9efdf45-46a2-4157-8e6c-XXXXXXXXXX'}, 'parent_device': '0edeaee5-8436-4b91-b6b5-XXXXXXXXXX', 'custom': None, 'attributes': {'available': None}}
2020-11-06 19:20:26 DEBUG (MainThread) [pyhiveapi.custom_logging] Getting hive device info
2020-11-06 19:20:26 DEBUG (MainThread) [pyhiveapi.custom_logging] Checking if new tokens are required
2020-11-06 19:20:26 DEBUG (MainThread) [pyhiveapi.custom_logging] Request is - get:https://beekeeper-uk.hivehome.com/1.0/nodes/all?products=true&devices=true&actions=true
2020-11-06 19:20:27 DEBUG (MainThread) [pyhiveapi.custom_logging] Response is - 200
2020-11-06 19:20:56 DEBUG (MainThread) [pyhiveapi.custom_logging] Getting hot water data.
2020-11-06 19:20:56 DEBUG (MainThread) [pyhiveapi.custom_logging] Device update {'hive_id': '84dfaef3-93c5-4aab-9530-XXXXXXXXXX', 'hive_name': 'Ground Floor', 'hive_type': 'hotwater', 'ha_name': 'Ground Floor', 'ha_type': 'water_heater', 'device_id': 'c155cc26-4ce0-42ef-8a57-XXXXXXXXXX', 'device_name': 'Ground Floor', 'current_operation': 'OFF', 'device_data': {'online': True, 'presenceLastChanged': 1603418475672, 'model': 'SLT3', 'version': '05060212', 'manufacturer': 'Computime', 'upgrade': {'available': False, 'version': '05060212', 'progress': 100, 'upgrading': False, 'status': 'COMPLETE'}, 'power': 'battery', 'signal': 100, 'battery': 100, 'capabilities': ['INFORMATION', 'RENAME', 'HEATING_ALERTS', 'GEOLOCATION', 'HOLIDAY_MODE', 'OPTIMUM_START'], 'modelVariant': 'SLT3b', 'zone': 'f9efdf45-46a2-4157-8e6c-XXXXXXXXXX'}, 'parent_device': '0edeaee5-8436-4b91-b6b5-XXXXXXXXXX', 'custom': None, 'attributes': {'available': None}}
2020-11-06 19:21:13 DEBUG (MainThread) [pyhiveapi.custom_logging] Checking if new tokens are required
2020-11-06 19:21:13 DEBUG (MainThread) [pyhiveapi.custom_logging] Request is - post:https://beekeeper-uk.hivehome.com/1.0/nodes/hotwater/84dfaef3-93c5-4aab-9530-XXXXXXXXXX
2020-11-06 19:21:13 DEBUG (MainThread) [pyhiveapi.custom_logging] Response is - 500
2020-11-06 19:21:13 ERROR (MainThread) [pyhiveapi.custom_logging] ERROR - Received 500 response from API.
2020-11-06 19:21:14 DEBUG (MainThread) [pyhiveapi.custom_logging] Getting hive device info
2020-11-06 19:21:14 DEBUG (MainThread) [pyhiveapi.custom_logging] Checking if new tokens are required
2020-11-06 19:21:14 DEBUG (MainThread) [pyhiveapi.custom_logging] Request is - get:https://beekeeper-uk.hivehome.com/1.0/nodes/all?products=true&devices=true&actions=true
2020-11-06 19:21:15 DEBUG (MainThread) [pyhiveapi.custom_logging] Response is - 200
2020-11-06 19:21:15 DEBUG (MainThread) [pyhiveapi.custom_logging] Getting hot water data.
2020-11-06 19:21:15 DEBUG (MainThread) [pyhiveapi.custom_logging] Device update {'hive_id': '84dfaef3-93c5-4aab-9530-XXXXXXXXXX', 'hive_name': 'Ground Floor', 'hive_type': 'hotwater', 'ha_name': 'Ground Floor', 'ha_type': 'water_heater', 'device_id': 'c155cc26-4ce0-42ef-8a57-XXXXXXXXXX', 'device_name': 'Ground Floor', 'current_operation': 'OFF', 'device_data': {'online': True, 'presenceLastChanged': 1603418475672, 'model': 'SLT3', 'version': '05060212', 'manufacturer': 'Computime', 'upgrade': {'available': False, 'version': '05060212', 'progress': 100, 'upgrading': False, 'status': 'COMPLETE'}, 'power': 'battery', 'signal': 100, 'battery': 100, 'capabilities': ['INFORMATION', 'RENAME', 'HEATING_ALERTS', 'GEOLOCATION', 'HOLIDAY_MODE', 'OPTIMUM_START'], 'modelVariant': 'SLT3b', 'zone': 'f9efdf45-46a2-4157-8e6c-XXXXXXXXXX'}, 'parent_device': '0edeaee5-8436-4b91-b6b5-XXXXXXXXXX', 'custom': None, 'attributes': {'available': None}}
```

**Comment by CaptInsano** [comment]
I turned on the "All" debugging option and sifted through the logs:

When when I have the hotwater turned on via the android app the homeassistant integration reports no change  in these devices:

```
2020-11-06 19:51:43 DEBUG (MainThread) [pyhiveapi.custom_logging] Device update {'hive_id': '84dfaef3-93c5-4aab-9530-XXXXXXXX', 'hive_name': 'Ground Floor', 'hive_type': 'Hotwater_State', 'ha_name': 'Ground Floor State', 'ha_type': 'sensor', 'device_id': 'c155cc26-4ce0-42ef-8a57-XXXXXXXX', 'device_name': 'Ground Floor', 'hub_id': None, 'device_data': {'online': True, 'presenceLastChanged': 1603418475672, 'model': 'SLT3', 'version': '05060212', 'manufacturer': 'Computime', 'upgrade': {'available': False, 'version': '05060212', 'progress': 100, 'upgrading': False, 'status': 'COMPLETE'}, 'power': 'battery', 'signal': 100, 'battery': 100, 'capabilities': ['INFORMATION', 'RENAME', 'HEATING_ALERTS', 'GEOLOCATION', 'HOLIDAY_MODE', 'OPTIMUM_START'], 'modelVariant': 'SLT3b', 'zone': 'f9efdf45-46a2-4157-8e6c-XXXXXXXX'}, 'custom': True, 'state': 'OFF', 'parent_device': '0edeaee5-8436-4b91-b6b5-XXXXXXXX'}

2020-11-06 19:51:43 DEBUG (MainThread) [pyhiveapi.custom_logging] Device update {'hive_id': '84dfaef3-93c5-4aab-9530-XXXXXXXX', 'hive_name': 'Ground Floor', 'hive_type': 'Hotwater_Mode', 'ha_name': 'Ground Floor Mode', 'ha_type': 'sensor', 'device_id': 'c155cc26-4ce0-42ef-8a57-XXXXXXXX', 'device_name': 'Ground Floor', 'hub_id': None, 'device_data': {'online': True, 'presenceLastChanged': 1603418475672, 'model': 'SLT3', 'version': '05060212', 'manufacturer': 'Computime', 'upgrade': {'available': False, 'version': '05060212', 'progress': 100, 'upgrading': False, 'status': 'COMPLETE'}, 'power': 'battery', 'signal': 100, 'battery': 100, 'capabilities': ['INFORMATION', 'RENAME', 'HEATING_ALERTS', 'GEOLOCATION', 'HOLIDAY_MODE', 'OPTIMUM_START'], 'modelVariant': 'SLT3b', 'zone': 'f9efdf45-46a2-4157-8e6c-XXXXXXXX'}, 'custom': True, 'state': 'OFF', 'parent_device': '0edeaee5-8436-4b91-b6b5-XXXXXXXX'}

2020-11-06 19:51:43 DEBUG (MainThread) [pyhiveapi.custom_logging] Device update {'hive_id': '84dfaef3-93c5-4aab-9530-XXXXXXXX', 'hive_name': 'Ground Floor', 'hive_type': 'Hotwater_Boost', 'ha_name': 'Ground Floor Boost', 'ha_type': 'sensor', 'device_id': 'c155cc26-4ce0-42ef-8a57-XXXXXXXX', 'device_name': 'Ground Floor', 'hub_id': None, 'device_data': {'online': True, 'presenceLastChanged': 1603418475672, 'model': 'SLT3', 'version': '05060212', 'manufacturer': 'Computime', 'upgrade': {'available': False, 'version': '05060212', 'progress': 100, 'upgrading': False, 'status': 'COMPLETE'}, 'power': 'battery', 'signal': 100, 'battery': 100, 'capabilities': ['INFORMATION', 'RENAME', 'HEATING_ALERTS', 'GEOLOCATION', 'HOLIDAY_MODE', 'OPTIMUM_START'], 'modelVariant': 'SLT3b', 'zone': 'f9efdf45-46a2-4157-8e6c-XXXXXXXX'}, 'custom': True, 'state': 'OFF', 'parent_device': '0edeaee5-8436-4b91-b6b5-XXXXXXXX'}

2020-11-06 19:51:43 DEBUG (MainThread) [pyhiveapi.custom_logging] action update {'hive_id': '07dfeb38-a9e1-4a81-9c2c-XXXXXXXX', 'hive_name': 'Boost Hot Water', 'hive_type': 'action', 'ha_name': 'Boost Hot Water', 'ha_type': 'switch', 'state': True, 'power_usage': None, 'device_data': {}, 'custom': None}
```

**Comment by KJonline** [comment]
Thanks @CaptInsano please can you switch on the extra debugging category also and re run as I will be able to trace using that to the exact function being called to get the 500 api response

**Comment by CaptInsano** [comment]
Enabled "All" and "Extra" debug options & restarted HomeAssistant:


On restart Hot Water was on "Schedule"
@21:53:49 Hot Water was turned "On"
@21:55:21 How Water was turned "Off"


I am including whole log as I am not sure what is relevant or not (Unique IDs removed)

https://hastebin.com/opejikipej.sql

(Log too long to post on github)

**Comment by KJonline** [comment]
@CaptInsano I have just released beta 16 which has a hotwater fix in it, I believe it was falsely reporting offline causing is to report the previous status.

**Comment by CaptInsano** [comment]
Amazing stuff! Things defo working better:

![image](https://user-images.githubusercontent.com/332478/98484838-0e4ee180-220a-11eb-9bcc-af077f64999d.png)

Green Highlights:
Boost reporting Correctly
Mode reporting Correctly

Orange Highlights:
Previous entity (Ground Floor State (for hotwater)) now unavailable, not sure is this is expected with new release.
"Hot Water" entity (at bottom) is correctly controlling hot water but not reporting it on the main page.

![image](https://user-images.githubusercontent.com/332478/98484950-d72d0000-220a-11eb-90f8-f60be658dd38.png)

 
Also is "eco" supposed to mean schedule yeah? Choosing "eco" enables schedule, just wondering if it should say Schedule instead of "eco".

Seriously appreciate all your work on this project dev!! 

I now have a fully working homeassistant/hive integration with 3 Zone Heating + Hot Water control!

**Comment by KJonline** [comment]
Yes unfortunately we are limited to home assistant modes we can't use our own so the closest we thought to schedule, the only way to get this changed is to suggest a home assistant architecture change. If something is reporting unavailable I wonder if I have missed one of the checks to see if the device is offline. once of the changes to this release is if a device goes offline in hive then it will report as unavailable in Home Assistant as you can no longer control it.

**Comment by CaptInsano** [comment]
I wonder if "Ground Floor State"(for Hotwater) is now only a duplicate of the "Hot Water" entity:


Previously I had these 2 entities:

sensor.ground_floor_state_2 (now unavailable)
water_heater.hotwater

I am pretty sure that they both would have reported the same thing (On|Off|Eco), yes?

If so, then there is nothing really missing and I can remove the sensor.ground_floor_state_2 entity from my homeassistant.

**Comment by KJonline** [comment]
@CaptInsano I would remove the unavailable ones and restart to see if they return. that will indicate if they are meant to be there but are reporting incorrectly

**Comment by CaptInsano** [comment]
I removed the entity sensor.ground_floor_state_2, and it remained gone after restart.

It must not be needed anymore!

Issue closed with my sincerest thanks for all your work!!
