### ISSUE TITLE
[BUG] Error in log Update for binary_sensor.bathroom fails

### ISSUE THREAD

**Issue by perjury** [Pyhive/HA-Hive-Custom-Component#68]
**Describe the bug**
Getting errors in the Log
Logger: homeassistant.helpers.entity
Source: custom_components/hive/binary_sensor.py:93
First occurred: 21 February 2021, 22:25:00 (13 occurrences)
Last logged: 10:40:11

Update for binary_sensor.bathroom fails
Update for binary_sensor.hall_sensor fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 278, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 482, in async_device_update
    await task
  File "/config/custom_components/hive/binary_sensor.py", line 93, in async_update
    await self.hive.session.updateData(self.device)
  File "/usr/local/lib/python3.8/site-packages/pyhiveapi/session.py", line 130, in updateData
    await self.getDevices(device["hiveID"])
  File "/usr/local/lib/python3.8/site-packages/pyhiveapi/session.py", line 150, in getDevices
    api_resp_d = await self.api.getAll()
  File "/usr/local/lib/python3.8/site-packages/pyhiveapi/api/hive_async_api.py", line 158, in getAll
    await self.request("get", url)
  File "/usr/local/lib/python3.8/site-packages/pyhiveapi/api/hive_async_api.py", line 91, in request
    await self.logger.LOGGER.error(
TypeError: object NoneType can't be used in 'await' expression

**Additional context**
Doesn't actually seem to be causing any problems - the sensors still seem to be working and triggering automations - I just don't like seeing ERROR in my log :-)

**Comment by KJonline** [comment]
This should be fixed in 2021.4.0
