### ISSUE TITLE
[BUG] KeyError: 'token'

### ISSUE THREAD

**Issue by alexolivier** [Pyhive/HA-Hive-Custom-Component#77]
It appears something has changed with how authorization works with the Hive endpoint being used

**Desktop (please complete the following information):**

- Home Assistant 2021.3.4

```
Logger: homeassistant.config_entries
Source: custom_components/hive/__init__.py:76
First occurred: 11:22:44 (1 occurrences)
Last logged: 11:22:44

Error setting up entry alex@alexolivier.me for hive
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/apyhiveapi/api/hive_async_api.py", line 61, in request
    {"authorization": self.session.tokens.tokenData["token"]}
KeyError: 'token'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 248, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/hive/__init__.py", line 76, in async_setup_entry
    devices = await hive.session.startSession(hive_config)
  File "/usr/local/lib/python3.8/site-packages/apyhiveapi/session.py", line 264, in startSession
    await self.getDevices("No_ID")
  File "/usr/local/lib/python3.8/site-packages/apyhiveapi/session.py", line 201, in getDevices
    await self.hiveRefreshTokens()
  File "/usr/local/lib/python3.8/site-packages/apyhiveapi/session.py", line 173, in hiveRefreshTokens
    updated = await self.api.refreshTokens()
  File "/usr/local/lib/python3.8/site-packages/apyhiveapi/api/hive_async_api.py", line 126, in refreshTokens
    await self.request("post", url, data=jsc)
  File "/usr/local/lib/python3.8/site-packages/apyhiveapi/api/hive_async_api.py", line 68, in request
    raise NoApiToken
apyhiveapi.helper.hive_exceptions.NoApiToken
```

**Comment by alexolivier** [comment]
Deleting the integration and re-adding solved it

**Comment by KJonline** [comment]
@alexolivier yes the latest release was a breaking change which required removing and re-adding it.
