### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by djdaveb** [Pyhive/HA-Hive-Custom-Component#79]
Hi. Ive lost all connection to hive. All my sensors and switches are showing unavailable

![Screenshot_2021-03-28-15-40-18-35_c3a231c25ed346e59462e84656a70e50](https://user-images.githubusercontent.com/80234749/112756201-0e465700-8fdc-11eb-8d60-207c2eb8ffd5.jpg)

Is it something my side. Or hive api?

**Comment by KJonline** [comment]
Have you tried a restart have you got any errors in the logs?

**Comment by djdaveb** [comment]
Hi. I completely forgot to add the logs. It seems to be pointing towards an api token 

2021-03-28 15:44:31 WARNING (MainThread) [homeassistant.loader] You are using a custom integration hive which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-03-28 15:44:31 WARNING (MainThread) [homeassistant.loader] You are using a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-03-28 15:44:47 WARNING (MainThread) [homeassistant.components.webhook] Received message for unregistered webhook 51a70801e774e8d805cb5e32bbe89695c0ae1353a7660d3d9e3b146925702acd from 192.168.0.170
2021-03-28 15:44:54 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry y.(removed)@blueyonder.co.uk for hive
Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/apyhiveapi/api/hive_async_api.py", line 61, in request
{"authorization": self.session.tokens.tokenData["token"]}
KeyError: 'token'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 248, in async_setup
result = await component.async_setup_entry(hass, self) # type: ignore
File "/config/custom_components/hive/__init__.py", line 76, in async_setup_entry
devices = await hive.session.startSession(hive_config)
File "/usr/local/lib/python3.8/site-packages/apyhiveapi/session.py", line 264, in startSession
await self.getDevices("No_ID")
File "/usr/local/lib/python3.8/site-packages/apyhiveapi/session.py", line 201, in getDevices
await self.hiveRefreshTokens()
File "/usr/local/lib/python3.8/site-packages/apyhiveapi/session.py", line 173, in hiveRefreshTokens
updated = await self.api.refreshTokens()
File "/usr/local/lib/python3.8/site-packages/apyhiveapi/api/hive_async_api.py", line 126, in refreshTokens
await self.request("post", url, data=jsc)
File "/usr/local/lib/python3.8/site-packages/apyhiveapi/api/hive_async_api.py", line 68, in request
raise NoApiToken
apyhiveapi.helper.hive_exceptions.NoApiToken

Be great to get it up and running again. As i run an automation to stop hive setting random temps.

Cheers 😊

**Comment by KJonline** [comment]
I take it you have updated to version 2021.3.1? This update is a breaking change and requires you to delete your integration from the integrations page within the home assistant configuration (not HACS)

Once done the integration needs setting backup again

**Comment by djdaveb** [comment]
You sir are a legend. Something so simple 🤣🤣 thank you👌👌
