### ISSUE TITLE
Add support for Hive 2-Factor Authentication

### ISSUE THREAD

**Issue by ellnic** [Pyhive/HA-Hive-Custom-Component#9]
I recently moved to your custom component and I love it :) Thanks for your hard work.

One thing I noticed is that after installing it, my phone got spammed with 2FA requests and I had to disable 2FA. With 2FA disabled, obviously things work as expected. I thought I could re-enable it afterwards like I did with the HA core component, but it doesn't seem to allow this, and I get spammed with 2FA requests again. 

Would it be possible to add something to allow the entering of the 2FA codes? 

Thanks :)

**Comment by upstairs-at-erics** [comment]
Further to this, Hive have now made it impossible to view or access Hive Camera without 2fa enabled. This means that many are now having to decide whether to ditch their HA integrations or ditch their (very expensive) Hive View Cameras. So I would like to second the feature request as a fairly urgent requirement if the integration is to survive.

**Comment by ellnic** [comment]
Do you mean they're only rolling out the "no camera access without 2FA" or just 2FA itself? I got an email about 2FA about 3 months ago (roughly). I only have the thermostat though. I'm not really ok with turning it off now it's available but I have a lot of automations (especially this time of year) that integrate with Hive.

**Comment by KJonline** [comment]
Hi all, some good news I have managed to work out the 2fa authentication for hive. And I am currently building it into the next version of the integration,along with other changes.

**Comment by upstairs-at-erics** [comment]
that is excellent news. Thank you so much.

**Comment by KJonline** [comment]
Hi All, Please can you upgrade to beta 10 via HACS and retry logging in 2FA is support by UI only not YAML

**Comment by ellnic** [comment]
This is great, thank you. I updated to b10, and removed my existing hive config from the YAML and restarted HA. I then went to integrations and added hive. I am presented with the 2FA prompt, but then I get an unknown error:

![image](https://user-images.githubusercontent.com/16370944/98345005-f90c6400-200b-11eb-9304-95c6754f2db9.jpeg)

What can I provide to help you debug, not sure where the integration logs are.

**Comment by ellnic** [comment]
Don't worry, I think I found it:


```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 18, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 72, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 127, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 129, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 169, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 60, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 106, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 156, in async_configure
    result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 204, in _async_handle_step
    result: Dict = await getattr(flow, method)(user_input)
  File "/config/custom_components/hive/config_flow.py", line 107, in async_step_2fa
    result = await self.hive_auth.sms_2fa(user_input["2fa"], self.tokens)
  File "/usr/local/lib/python3.8/site-packages/pyhiveapi/hiveauth.py", line 270, in sms_2fa
    result = await self.loop.run_in_executor(None,
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.8/site-packages/botocore/client.py", line 648, in _make_api_call
    request_dict = self._convert_to_request_dict(
  File "/usr/local/lib/python3.8/site-packages/botocore/client.py", line 696, in _convert_to_request_dict
    request_dict = self._serializer.serialize_to_request(
  File "/usr/local/lib/python3.8/site-packages/botocore/validate.py", line 297, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Invalid type for parameter Session, value: None, type: <class 'NoneType'>, valid types: <class 'str'>

```

**Comment by KJonline** [comment]
@ellnic i did a lot of upgrades last night, please can you upgrade to beta 15 and retry.

**Comment by ellnic** [comment]
@KJonline brilliant. That's done it. I can now authenticate using 2FA. You're a star 👍

**Comment by ellnic** [comment]
Sorry, quick question (and apologies that it's not related to this issue) but how does your integration call for a boost? My previous config doesn't seem to work, I get this:

`Failed to call service script/boost_heating_23c_40m. 'NoneType' object has no attribute 'turn_boost_on'`

**Comment by KJonline** [comment]
Are you using the service provided by the integration or one you have written, if your using the service as part of the integration. I have not reviewed those yet, please keep in mind the next upgrade which includes 2fa is beta and  all functionality may or may not work depending on what devices you have and what functionality you use.

**Comment by ellnic** [comment]
It's just the one provided by the integration. I have scripts that look something like this:

```
boost_heating_23c_40m:
  sequence:
  - data:
      entity_id: climate.hive_hall_stat
      temperature: '23'
      time_period: 00:40:00
    service: hive.boost_heating
```

I literally only have the Stat, and use boost mostly in automations.

**Comment by KJonline** [comment]
Closing this issue 2fa support is in the latest beta.

A separate issue has been created for the boost service issues.

**Comment by ellnic** [comment]
Thank you. Much appreciated. :-)
